# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180927_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
