# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_upload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upload_image',
        ),
        migrations.AddField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
